name: build-and-release

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore

      - name: Build (Release)
        run: dotnet build -c Release --no-restore

      - name: Upload DLL artifact
        uses: actions/upload-artifact@v4
        with:
          name: FriendlyNoTeammateBullets-dll
          path: |
            **/bin/Release/**/*.dll
          if-no-files-found: error

  release:
    if: startsWith(github.ref, 'refs/tags/')
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: FriendlyNoTeammateBullets-dll
          path: dist

      - name: Create GitHub Release and upload DLLs
        uses: softprops/action-gh-release@v2
        with:
          files: dist/**/*.dll
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
